### ISSUE TITLE
`0.05` still has 5.10+ dependency, due to release process

### ISSUE THREAD

**Issue by astj** [tarao/perl5-Test-MockTime-HiRes#5]
With #3 , this module should work 5.8+, but released `0.05` still requires 5.10+.
I checked the commit log and found it's maybe due to release process of 0.05. Your release commit https://github.com/tarao/perl5-Test-MockTime-HiRes/commit/9531d122272f487a5205d629ea204d116d15588d doesn't include #3 , which merged at https://github.com/tarao/perl5-Test-MockTime-HiRes/commit/d0e8b88de4547e92f26994499df761ddef900d92 . (You `minil release`ed before `git pull`?)
As a result, released 0.05 doesn't include 5.8+ support code and metadeta, but declared 'Support Perl 5.8' in Changelog.

Would you like to release newer version which _really_ includes 5.8 support code and metadata?

**Comment by tarao** [comment]
Oh, sorry, I will re-release it tomorrow.

**Comment by astj** [comment]
Thanks :pray:

**Comment by tarao** [comment]
Released: http://search.cpan.org/~tarao/Test-MockTime-HiRes-0.06/

**Comment by astj** [comment]
Thanks!!!
